# To generate new quiz questions just copy and paste the below URL and assign that to question_data
# https://opentdb.com/api.php?amount=10&type=boolean


# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]

# question_data = [
#     {"category": "Entertainment: Video Games",
#      "type": "boolean",
#      "difficulty": "easy",
#      "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "General Knowledge",
#      "type": "boolean",
#      "difficulty": "easy",
#      "question": "When you cry in space, your tears stick to your face.",
#      "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Film",
#      "type": "boolean",
#      "difficulty": "easy",
#      "question": "In the movie The Revenant, DiCaprio's character hunts down the killer of his son.",
#      "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Science: Computers",
#      "type": "boolean",
#      "difficulty": "medium",
#      "question": "The first dual-core CPU was the Intel Pentium D.",
#      "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Sports",
#      "type": "boolean",
#      "difficulty": "medium",
#      "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
#      "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "History",
#      "type": "boolean",
#      "difficulty": "medium",
#      "question": "The Hundred Years War was fought for more than a hundred years.",
#      "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Entertainment: Video Games",
#      "type": "boolean",
#      "difficulty": "easy",
#      "question": "In Pokemon, Arbok evolves into Seviper.",
#      "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Cartoon & Animations",
#      "type": "boolean", "difficulty": "easy",
#      "question": "Waylon Smithers from 'The Simpsons' was originally black when he first appeared in the series.",
#      "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Science & Nature",
#      "type": "boolean",
#      "difficulty": "easy",
#      "question": "Water always boils at 100C, 212F, 373.15K, no matter where you are.",
#      "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Entertainment: Video Games",
#      "type": "boolean",
#      "difficulty": "medium",
#      "question": "The game Garry's Mod originally took assets and codes from the popular Half Life 2 mod JBmod.",
#      "correct_answer": "True",
#      "incorrect_answers": ["False"]}]

question_data = {"response_code": 0, "results": [
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy", "question": "&quot;Undertale&quot; is an RPG created by Toby Fox and released in 2015.",
     "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
                                                                 "question": "The &quot;Berenstein Bears&quot; is the correct spelling of the educational children&#039;s book series&#039; name.",
                                                                 "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
     "question": "In &quot;Portal 2&quot;, Cave Johnson started out Aperture Science as a shower curtain company.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium", "question": "You could walk from Norway to North Korea while only passing through Russia.",
     "correct_answer": "True", "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                                                 "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
                                                                 "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium", "question": "Zero factorial is equal to zero. ", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium", "question": "A &#039;Millinillion&#039; is a real number.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Politics", "type": "boolean", "difficulty": "hard",
                                       "question": "George Clinton, Vice President of the United States (1805-1812), is an ancestor of President Bill Clinton.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium", "question": "&quot;Santa Claus&quot; is a variety of melon.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "hard", "question": "The man that shot Alexander Hamilton was named Aaron Burr.", "correct_answer": "True",
     "incorrect_answers": ["False"]}]}
